apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "satis.fullname" . }}-config
  labels:
    app: {{ template "satis.fullname" . }}
data:
  satis.json: |-
{{ .Values.satis.config | indent 4 }}
  # Nginx
  default.conf: |-
{{ .Values.nginx.config | indent 4 }}
