apiVersion: v1
kind: Service
metadata:
  name: {{ template "satis.fullname" . }}
  labels:
    app: {{ template "satis.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: {{ template "satis.name" . }}
    release: {{ .Release.Name }}
